description: Playbook Design System
figma: https://www.figma.com/community/file/1320084191991515570
frameworks:
  - React
homepage: https://playbook.powerapp.cloud/
name: Playbook
repository: https://github.com/powerhome/playbook
styling: Sass
